
package com.cbp2.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurchaseOrderWS", targetNamespace = "http://service.cbp.ws.cbp2.com/", wsdlLocation = "http://18.223.203.6:8080/CBP-2/PurchaseOrderWS?WSDL")
public class PurchaseOrderWS_Service
    extends Service
{

    private final static URL PURCHASEORDERWS_WSDL_LOCATION;
    private final static WebServiceException PURCHASEORDERWS_EXCEPTION;
    private final static QName PURCHASEORDERWS_QNAME = new QName("http://service.cbp.ws.cbp2.com/", "PurchaseOrderWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.223.203.6:8080/CBP-2/PurchaseOrderWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURCHASEORDERWS_WSDL_LOCATION = url;
        PURCHASEORDERWS_EXCEPTION = e;
    }

    public PurchaseOrderWS_Service() {
        super(__getWsdlLocation(), PURCHASEORDERWS_QNAME);
    }

    public PurchaseOrderWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURCHASEORDERWS_QNAME, features);
    }

    public PurchaseOrderWS_Service(URL wsdlLocation) {
        super(wsdlLocation, PURCHASEORDERWS_QNAME);
    }

    public PurchaseOrderWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURCHASEORDERWS_QNAME, features);
    }

    public PurchaseOrderWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurchaseOrderWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurchaseOrderWS
     */
    @WebEndpoint(name = "PurchaseOrderWSPort")
    public PurchaseOrderWS getPurchaseOrderWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp2.com/", "PurchaseOrderWSPort"), PurchaseOrderWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurchaseOrderWS
     */
    @WebEndpoint(name = "PurchaseOrderWSPort")
    public PurchaseOrderWS getPurchaseOrderWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp2.com/", "PurchaseOrderWSPort"), PurchaseOrderWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURCHASEORDERWS_EXCEPTION!= null) {
            throw PURCHASEORDERWS_EXCEPTION;
        }
        return PURCHASEORDERWS_WSDL_LOCATION;
    }

}
