
package com.cbp3.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AfiliacionServiceWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", wsdlLocation = "http://18.223.203.6:8080/CBP-3/AfiliacionServiceWS?WSDL")
public class AfiliacionServiceWS_Service
    extends Service
{

    private final static URL AFILIACIONSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException AFILIACIONSERVICEWS_EXCEPTION;
    private final static QName AFILIACIONSERVICEWS_QNAME = new QName("http://service.cbp.ws.cbp3.com/", "AfiliacionServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.223.203.6:8080/CBP-3/AfiliacionServiceWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AFILIACIONSERVICEWS_WSDL_LOCATION = url;
        AFILIACIONSERVICEWS_EXCEPTION = e;
    }

    public AfiliacionServiceWS_Service() {
        super(__getWsdlLocation(), AFILIACIONSERVICEWS_QNAME);
    }

    public AfiliacionServiceWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AFILIACIONSERVICEWS_QNAME, features);
    }

    public AfiliacionServiceWS_Service(URL wsdlLocation) {
        super(wsdlLocation, AFILIACIONSERVICEWS_QNAME);
    }

    public AfiliacionServiceWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AFILIACIONSERVICEWS_QNAME, features);
    }

    public AfiliacionServiceWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AfiliacionServiceWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AfiliacionServiceWS
     */
    @WebEndpoint(name = "AfiliacionServiceWSPort")
    public AfiliacionServiceWS getAfiliacionServiceWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "AfiliacionServiceWSPort"), AfiliacionServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AfiliacionServiceWS
     */
    @WebEndpoint(name = "AfiliacionServiceWSPort")
    public AfiliacionServiceWS getAfiliacionServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "AfiliacionServiceWSPort"), AfiliacionServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AFILIACIONSERVICEWS_EXCEPTION!= null) {
            throw AFILIACIONSERVICEWS_EXCEPTION;
        }
        return AFILIACIONSERVICEWS_WSDL_LOCATION;
    }

}
