
package com.cbp3.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlmacenServiceWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", wsdlLocation = "http://18.223.203.6:8080/CBP-3/AlmacenServiceWS?WSDL")
public class AlmacenServiceWS_Service
    extends Service
{

    private final static URL ALMACENSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException ALMACENSERVICEWS_EXCEPTION;
    private final static QName ALMACENSERVICEWS_QNAME = new QName("http://service.cbp.ws.cbp3.com/", "AlmacenServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.223.203.6:8080/CBP-3/AlmacenServiceWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALMACENSERVICEWS_WSDL_LOCATION = url;
        ALMACENSERVICEWS_EXCEPTION = e;
    }

    public AlmacenServiceWS_Service() {
        super(__getWsdlLocation(), ALMACENSERVICEWS_QNAME);
    }

    public AlmacenServiceWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALMACENSERVICEWS_QNAME, features);
    }

    public AlmacenServiceWS_Service(URL wsdlLocation) {
        super(wsdlLocation, ALMACENSERVICEWS_QNAME);
    }

    public AlmacenServiceWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALMACENSERVICEWS_QNAME, features);
    }

    public AlmacenServiceWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlmacenServiceWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlmacenServiceWS
     */
    @WebEndpoint(name = "AlmacenServiceWSPort")
    public AlmacenServiceWS getAlmacenServiceWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "AlmacenServiceWSPort"), AlmacenServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlmacenServiceWS
     */
    @WebEndpoint(name = "AlmacenServiceWSPort")
    public AlmacenServiceWS getAlmacenServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "AlmacenServiceWSPort"), AlmacenServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALMACENSERVICEWS_EXCEPTION!= null) {
            throw ALMACENSERVICEWS_EXCEPTION;
        }
        return ALMACENSERVICEWS_WSDL_LOCATION;
    }

}
