
package com.cbp3.ws.cbp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AlmacenServiceWS", targetNamespace = "http://service.cbp.ws.cbp3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AlmacenServiceWS {


    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.TipoZona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTipoZonaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListTipoZonaWS")
    @ResponseWrapper(localName = "listTipoZonaWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListTipoZonaWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listTipoZonaWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listTipoZonaWSResponse")
    public List<TipoZona> listTipoZonaWS();

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.RelacionZonas>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaRelacionZonasWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaRelacionZonasWS")
    @ResponseWrapper(localName = "listaRelacionZonasWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaRelacionZonasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaRelacionZonasWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaRelacionZonasWSResponse")
    public List<RelacionZonas> listaRelacionZonasWS();

    /**
     * 
     * @param dto
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAditionaInformationAlmacenWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.SaveAditionaInformationAlmacenWS")
    @ResponseWrapper(localName = "saveAditionaInformationAlmacenWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.SaveAditionaInformationAlmacenWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/saveAditionaInformationAlmacenWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/saveAditionaInformationAlmacenWSResponse")
    public RespuestaDTO saveAditionaInformationAlmacenWS(
        @WebParam(name = "dto", targetNamespace = "")
        AlmacenDTO dto);

    /**
     * 
     * @param numeroAlmacen
     * @param identificacionProducto
     * @param codigoUsuarioModifica
     * @param tipoAlmacen
     * @param direccion
     * @param identificacionOficina
     * @param fechaHoraModifica
     * @param nombreAlmacen
     * @param gerenteSucursal
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarAlmacenWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarAlmacenWS")
    @ResponseWrapper(localName = "modificarAlmacenWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarAlmacenWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarAlmacenWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarAlmacenWSResponse")
    public RespuestaDTO modificarAlmacenWS(
        @WebParam(name = "numeroAlmacen", targetNamespace = "")
        String numeroAlmacen,
        @WebParam(name = "nombreAlmacen", targetNamespace = "")
        String nombreAlmacen,
        @WebParam(name = "identificacionOficina", targetNamespace = "")
        long identificacionOficina,
        @WebParam(name = "identificacionProducto", targetNamespace = "")
        long identificacionProducto,
        @WebParam(name = "codigoUsuarioModifica", targetNamespace = "")
        long codigoUsuarioModifica,
        @WebParam(name = "fechaHoraModifica", targetNamespace = "")
        XMLGregorianCalendar fechaHoraModifica,
        @WebParam(name = "tipoAlmacen", targetNamespace = "")
        long tipoAlmacen,
        @WebParam(name = "direccion", targetNamespace = "")
        String direccion,
        @WebParam(name = "gerenteSucursal", targetNamespace = "")
        long gerenteSucursal);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.Warehouse>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaAlmacenesWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaAlmacenesWS")
    @ResponseWrapper(localName = "listaAlmacenesWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaAlmacenesWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaAlmacenesWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaAlmacenesWSResponse")
    public List<Warehouse> listaAlmacenesWS();

    /**
     * 
     * @param almacenActualId
     * @param fechaCargaDatos
     * @param almacenDestinoId
     * @param comentarios
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearRelacionAlmacenesWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearRelacionAlmacenesWS")
    @ResponseWrapper(localName = "crearRelacionAlmacenesWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearRelacionAlmacenesWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearRelacionAlmacenesWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearRelacionAlmacenesWSResponse")
    public RespuestaDTO crearRelacionAlmacenesWS(
        @WebParam(name = "almacenActualId", targetNamespace = "")
        Warehouse almacenActualId,
        @WebParam(name = "almacenDestinoId", targetNamespace = "")
        Warehouse almacenDestinoId,
        @WebParam(name = "comentarios", targetNamespace = "")
        String comentarios,
        @WebParam(name = "fechaCargaDatos", targetNamespace = "")
        XMLGregorianCalendar fechaCargaDatos);

    /**
     * 
     * @param almacenActualId
     * @param almacenDestinoId
     * @param codigoUsuarioModifica
     * @param fechaHoraModifica
     * @param comentarios
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarRelacionAlmacenesWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarRelacionAlmacenesWS")
    @ResponseWrapper(localName = "modificarRelacionAlmacenesWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarRelacionAlmacenesWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarRelacionAlmacenesWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarRelacionAlmacenesWSResponse")
    public RespuestaDTO modificarRelacionAlmacenesWS(
        @WebParam(name = "almacenActualId", targetNamespace = "")
        Warehouse almacenActualId,
        @WebParam(name = "almacenDestinoId", targetNamespace = "")
        Warehouse almacenDestinoId,
        @WebParam(name = "comentarios", targetNamespace = "")
        String comentarios,
        @WebParam(name = "codigoUsuarioModifica", targetNamespace = "")
        long codigoUsuarioModifica,
        @WebParam(name = "fechaHoraModifica", targetNamespace = "")
        XMLGregorianCalendar fechaHoraModifica);

    /**
     * 
     * @param descripcion
     * @param fechaCargaDatos
     * @param zonaNombre
     * @param tipoZonaId
     * @param idWarehouse
     * @param encargadoZona
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearZonaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearZonaWS")
    @ResponseWrapper(localName = "crearZonaWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearZonaWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearZonaWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearZonaWSResponse")
    public RespuestaDTO crearZonaWS(
        @WebParam(name = "zonaNombre", targetNamespace = "")
        String zonaNombre,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "fechaCargaDatos", targetNamespace = "")
        XMLGregorianCalendar fechaCargaDatos,
        @WebParam(name = "encargadoZona", targetNamespace = "")
        Empleado encargadoZona,
        @WebParam(name = "tipoZonaId", targetNamespace = "")
        TipoZona tipoZonaId,
        @WebParam(name = "idWarehouse", targetNamespace = "")
        Warehouse idWarehouse);

    /**
     * 
     * @param descripcion
     * @param zonaNombre
     * @param tipoZonaId
     * @param codigoUsuarioModifica
     * @param idWarehouse
     * @param fechaHoraModifica
     * @param zonaId
     * @param encargadoZona
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarZonaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarZonaWS")
    @ResponseWrapper(localName = "modificarZonaWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarZonaWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarZonaWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarZonaWSResponse")
    public RespuestaDTO modificarZonaWS(
        @WebParam(name = "zonaId", targetNamespace = "")
        long zonaId,
        @WebParam(name = "zonaNombre", targetNamespace = "")
        String zonaNombre,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "encargadoZona", targetNamespace = "")
        Empleado encargadoZona,
        @WebParam(name = "tipoZonaId", targetNamespace = "")
        TipoZona tipoZonaId,
        @WebParam(name = "idWarehouse", targetNamespace = "")
        Warehouse idWarehouse,
        @WebParam(name = "codigoUsuarioModifica", targetNamespace = "")
        long codigoUsuarioModifica,
        @WebParam(name = "fechaHoraModifica", targetNamespace = "")
        XMLGregorianCalendar fechaHoraModifica);

    /**
     * 
     * @param numeroAlmacen
     * @return
     *     returns com.cbp3.ws.cbp.service.Warehouse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaAlmacenPorNumeroAlmacenWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaAlmacenPorNumeroAlmacenWS")
    @ResponseWrapper(localName = "consultaAlmacenPorNumeroAlmacenWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaAlmacenPorNumeroAlmacenWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaAlmacenPorNumeroAlmacenWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaAlmacenPorNumeroAlmacenWSResponse")
    public Warehouse consultaAlmacenPorNumeroAlmacenWS(
        @WebParam(name = "numeroAlmacen", targetNamespace = "")
        String numeroAlmacen);

    /**
     * 
     * @param idAlmacen
     * @return
     *     returns com.cbp3.ws.cbp.service.Warehouse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaAlmacenPorAlmacenIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaAlmacenPorAlmacenIdWS")
    @ResponseWrapper(localName = "consultaAlmacenPorAlmacenIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaAlmacenPorAlmacenIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaAlmacenPorAlmacenIdWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaAlmacenPorAlmacenIdWSResponse")
    public Warehouse consultaAlmacenPorAlmacenIdWS(
        @WebParam(name = "idAlmacen", targetNamespace = "")
        long idAlmacen);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.RelacionAlmacenes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaRelacionAlmacenesWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaRelacionAlmacenesWS")
    @ResponseWrapper(localName = "listaRelacionAlmacenesWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaRelacionAlmacenesWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaRelacionAlmacenesWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaRelacionAlmacenesWSResponse")
    public List<RelacionAlmacenes> listaRelacionAlmacenesWS();

    /**
     * 
     * @param dto
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearAlmacenWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearAlmacenWS")
    @ResponseWrapper(localName = "crearAlmacenWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearAlmacenWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearAlmacenWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearAlmacenWSResponse")
    public RespuestaDTO crearAlmacenWS(
        @WebParam(name = "dto", targetNamespace = "")
        AlmacenDTO dto);

    /**
     * 
     * @param fechaCargaDatos
     * @param zonaActualId
     * @param zonaDestinoId
     * @param comentarios
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearRelacionZonasWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearRelacionZonasWS")
    @ResponseWrapper(localName = "crearRelacionZonasWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearRelacionZonasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearRelacionZonasWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearRelacionZonasWSResponse")
    public RespuestaDTO crearRelacionZonasWS(
        @WebParam(name = "zonaActualId", targetNamespace = "")
        Zona zonaActualId,
        @WebParam(name = "zonaDestinoId", targetNamespace = "")
        Zona zonaDestinoId,
        @WebParam(name = "comentarios", targetNamespace = "")
        String comentarios,
        @WebParam(name = "fechaCargaDatos", targetNamespace = "")
        XMLGregorianCalendar fechaCargaDatos);

    /**
     * 
     * @param codigoUsuarioModifica
     * @param zonaActualId
     * @param zonaDestinoId
     * @param fechaHoraModifica
     * @param comentarios
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarRelacionZonasWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarRelacionZonasWS")
    @ResponseWrapper(localName = "modificarRelacionZonasWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarRelacionZonasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarRelacionZonasWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarRelacionZonasWSResponse")
    public RespuestaDTO modificarRelacionZonasWS(
        @WebParam(name = "zonaActualId", targetNamespace = "")
        Zona zonaActualId,
        @WebParam(name = "zonaDestinoId", targetNamespace = "")
        Zona zonaDestinoId,
        @WebParam(name = "comentarios", targetNamespace = "")
        String comentarios,
        @WebParam(name = "codigoUsuarioModifica", targetNamespace = "")
        long codigoUsuarioModifica,
        @WebParam(name = "fechaHoraModifica", targetNamespace = "")
        XMLGregorianCalendar fechaHoraModifica);

    /**
     * 
     * @param zonaId
     * @return
     *     returns com.cbp3.ws.cbp.service.Zona
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaZonaPorZonaIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaZonaPorZonaIdWS")
    @ResponseWrapper(localName = "consultaZonaPorZonaIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaZonaPorZonaIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaZonaPorZonaIdWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaZonaPorZonaIdWSResponse")
    public Zona consultaZonaPorZonaIdWS(
        @WebParam(name = "zonaId", targetNamespace = "")
        long zonaId);

    /**
     * 
     * @param descripcion
     * @param modulos
     * @param niveles
     * @param zonaId
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearEstanteriaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearEstanteriaWS")
    @ResponseWrapper(localName = "crearEstanteriaWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearEstanteriaWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearEstanteriaWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearEstanteriaWSResponse")
    public RespuestaDTO crearEstanteriaWS(
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "zonaId", targetNamespace = "")
        long zonaId,
        @WebParam(name = "modulos", targetNamespace = "")
        long modulos,
        @WebParam(name = "niveles", targetNamespace = "")
        long niveles);

    /**
     * 
     * @param descripcion
     * @param modulos
     * @param codigoUsuarioModifica
     * @param niveles
     * @param fechaHoraModificacion
     * @param estanteriaId
     * @param zonaId
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarEstanteriaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarEstanteriaWS")
    @ResponseWrapper(localName = "modificarEstanteriaWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarEstanteriaWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarEstanteriaWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/modificarEstanteriaWSResponse")
    public RespuestaDTO modificarEstanteriaWS(
        @WebParam(name = "estanteriaId", targetNamespace = "")
        long estanteriaId,
        @WebParam(name = "descripcion", targetNamespace = "")
        String descripcion,
        @WebParam(name = "zonaId", targetNamespace = "")
        long zonaId,
        @WebParam(name = "modulos", targetNamespace = "")
        long modulos,
        @WebParam(name = "niveles", targetNamespace = "")
        long niveles,
        @WebParam(name = "codigoUsuarioModifica", targetNamespace = "")
        long codigoUsuarioModifica,
        @WebParam(name = "fechaHoraModificacion", targetNamespace = "")
        XMLGregorianCalendar fechaHoraModificacion);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.Estanteria>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaEstanteriasWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaEstanteriasWS")
    @ResponseWrapper(localName = "listaEstanteriasWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaEstanteriasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaEstanteriasWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaEstanteriasWSResponse")
    public List<Estanteria> listaEstanteriasWS();

    /**
     * 
     * @param estanteriaId
     * @return
     *     returns com.cbp3.ws.cbp.service.Estanteria
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaEstanteriaPorEstanteriaIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaEstanteriaPorEstanteriaIdWS")
    @ResponseWrapper(localName = "consultaEstanteriaPorEstanteriaIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaEstanteriaPorEstanteriaIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaEstanteriaPorEstanteriaIdWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/consultaEstanteriaPorEstanteriaIdWSResponse")
    public Estanteria consultaEstanteriaPorEstanteriaIdWS(
        @WebParam(name = "estanteriaId", targetNamespace = "")
        long estanteriaId);

    /**
     * 
     * @param listZonaDTO
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearListaZonaWizzardWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearListaZonaWizzardWS")
    @ResponseWrapper(localName = "crearListaZonaWizzardWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearListaZonaWizzardWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearListaZonaWizzardWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/crearListaZonaWizzardWSResponse")
    public RespuestaDTO crearListaZonaWizzardWS(
        @WebParam(name = "listZonaDTO", targetNamespace = "")
        List<ZonaDTO> listZonaDTO);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.Zona>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listaZonasWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaZonasWS")
    @ResponseWrapper(localName = "listaZonasWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListaZonasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaZonasWSRequest", output = "http://service.cbp.ws.cbp3.com/AlmacenServiceWS/listaZonasWSResponse")
    public List<Zona> listaZonasWS();

}
