
package com.cbp3.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventarioServiceWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", wsdlLocation = "http://18.222.73.208:8080/CBP-3/InventarioServiceWS?WSDL")
public class InventarioServiceWS_Service
    extends Service
{

    private final static URL INVENTARIOSERVICEWS_WSDL_LOCATION;
    private final static WebServiceException INVENTARIOSERVICEWS_EXCEPTION;
    private final static QName INVENTARIOSERVICEWS_QNAME = new QName("http://service.cbp.ws.cbp3.com/", "InventarioServiceWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.222.73.208:8080/CBP-3/InventarioServiceWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTARIOSERVICEWS_WSDL_LOCATION = url;
        INVENTARIOSERVICEWS_EXCEPTION = e;
    }

    public InventarioServiceWS_Service() {
        super(__getWsdlLocation(), INVENTARIOSERVICEWS_QNAME);
    }

    public InventarioServiceWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTARIOSERVICEWS_QNAME, features);
    }

    public InventarioServiceWS_Service(URL wsdlLocation) {
        super(wsdlLocation, INVENTARIOSERVICEWS_QNAME);
    }

    public InventarioServiceWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTARIOSERVICEWS_QNAME, features);
    }

    public InventarioServiceWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventarioServiceWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventarioServiceWS
     */
    @WebEndpoint(name = "InventarioServiceWSPort")
    public InventarioServiceWS getInventarioServiceWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "InventarioServiceWSPort"), InventarioServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventarioServiceWS
     */
    @WebEndpoint(name = "InventarioServiceWSPort")
    public InventarioServiceWS getInventarioServiceWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "InventarioServiceWSPort"), InventarioServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTARIOSERVICEWS_EXCEPTION!= null) {
            throw INVENTARIOSERVICEWS_EXCEPTION;
        }
        return INVENTARIOSERVICEWS_WSDL_LOCATION;
    }

}
