
package com.cbp3.ws.cbp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventarioServiceWS", targetNamespace = "http://service.cbp.ws.cbp3.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventarioServiceWS {


    /**
     * 
     * @param idProvider
     * @return
     *     returns com.cbp3.ws.cbp.service.Provider
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaProveedorPorProveedorIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaProveedorPorProveedorIdWS")
    @ResponseWrapper(localName = "consultaProveedorPorProveedorIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaProveedorPorProveedorIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaProveedorPorProveedorIdWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaProveedorPorProveedorIdWSResponse")
    public Provider consultaProveedorPorProveedorIdWS(
        @WebParam(name = "idProvider", targetNamespace = "")
        long idProvider);

    /**
     * 
     * @param idTipoMovimiento
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.Movimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMovimientosByTipoMovimientoWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListMovimientosByTipoMovimientoWS")
    @ResponseWrapper(localName = "listMovimientosByTipoMovimientoWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListMovimientosByTipoMovimientoWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listMovimientosByTipoMovimientoWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listMovimientosByTipoMovimientoWSResponse")
    public List<Movimiento> listMovimientosByTipoMovimientoWS(
        @WebParam(name = "idTipoMovimiento", targetNamespace = "")
        long idTipoMovimiento);

    /**
     * 
     * @param idOrder
     * @return
     *     returns com.cbp3.ws.cbp.service.PurchaseOrder
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaPurchaseOrderPorPurchaseOrderIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaPurchaseOrderPorPurchaseOrderIdWS")
    @ResponseWrapper(localName = "consultaPurchaseOrderPorPurchaseOrderIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaPurchaseOrderPorPurchaseOrderIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaPurchaseOrderPorPurchaseOrderIdWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaPurchaseOrderPorPurchaseOrderIdWSResponse")
    public PurchaseOrder consultaPurchaseOrderPorPurchaseOrderIdWS(
        @WebParam(name = "idOrder", targetNamespace = "")
        long idOrder);

    /**
     * 
     * @param idWarehouse
     * @param idProduct
     * @param estanteriaId
     * @param comentario
     * @param zonaId
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearProductoUbicacionWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearProductoUbicacionWS")
    @ResponseWrapper(localName = "crearProductoUbicacionWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearProductoUbicacionWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/crearProductoUbicacionWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/crearProductoUbicacionWSResponse")
    public RespuestaDTO crearProductoUbicacionWS(
        @WebParam(name = "idProduct", targetNamespace = "")
        Product idProduct,
        @WebParam(name = "idWarehouse", targetNamespace = "")
        Warehouse idWarehouse,
        @WebParam(name = "zonaId", targetNamespace = "")
        Zona zonaId,
        @WebParam(name = "estanteriaId", targetNamespace = "")
        Estanteria estanteriaId,
        @WebParam(name = "comentario", targetNamespace = "")
        String comentario);

    /**
     * 
     * @param idWarehouse
     * @param idProduct
     * @param productoUbicacionId
     * @param estanteriaId
     * @param comentario
     * @param zonaId
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarProductoUbicacionWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarProductoUbicacionWS")
    @ResponseWrapper(localName = "modificarProductoUbicacionWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarProductoUbicacionWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/modificarProductoUbicacionWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/modificarProductoUbicacionWSResponse")
    public RespuestaDTO modificarProductoUbicacionWS(
        @WebParam(name = "productoUbicacionId", targetNamespace = "")
        long productoUbicacionId,
        @WebParam(name = "idProduct", targetNamespace = "")
        Product idProduct,
        @WebParam(name = "idWarehouse", targetNamespace = "")
        Warehouse idWarehouse,
        @WebParam(name = "zonaId", targetNamespace = "")
        Zona zonaId,
        @WebParam(name = "estanteriaId", targetNamespace = "")
        Estanteria estanteriaId,
        @WebParam(name = "comentario", targetNamespace = "")
        String comentario);

    /**
     * 
     * @param productoUbicacionId
     * @return
     *     returns com.cbp3.ws.cbp.service.ProductoUbicacion
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaProductoUbicacionsByIdProductoUbicacionWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaProductoUbicacionsByIdProductoUbicacionWS")
    @ResponseWrapper(localName = "consultaProductoUbicacionsByIdProductoUbicacionWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaProductoUbicacionsByIdProductoUbicacionWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaProductoUbicacionsByIdProductoUbicacionWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaProductoUbicacionsByIdProductoUbicacionWSResponse")
    public ProductoUbicacion consultaProductoUbicacionsByIdProductoUbicacionWS(
        @WebParam(name = "productoUbicacionId", targetNamespace = "")
        long productoUbicacionId);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.ProductoUbicacion>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProductoUbicacionWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListProductoUbicacionWS")
    @ResponseWrapper(localName = "listProductoUbicacionWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListProductoUbicacionWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listProductoUbicacionWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listProductoUbicacionWSResponse")
    public List<ProductoUbicacion> listProductoUbicacionWS();

    /**
     * 
     * @param tipoIdentificacionId
     * @param telefonoLocal
     * @param nombre
     * @param identificacionTercero
     * @param email
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearTerceroWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearTerceroWS")
    @ResponseWrapper(localName = "crearTerceroWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.CrearTerceroWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/crearTerceroWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/crearTerceroWSResponse")
    public RespuestaDTO crearTerceroWS(
        @WebParam(name = "tipoIdentificacionId", targetNamespace = "")
        Tipoidentificacion tipoIdentificacionId,
        @WebParam(name = "identificacionTercero", targetNamespace = "")
        String identificacionTercero,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "telefonoLocal", targetNamespace = "")
        String telefonoLocal);

    /**
     * 
     * @param tipoIdentificacionId
     * @param terceroId
     * @param telefonoLocal
     * @param nombre
     * @param identificacionTercero
     * @param email
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modificarTerceroWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarTerceroWS")
    @ResponseWrapper(localName = "modificarTerceroWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ModificarTerceroWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/modificarTerceroWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/modificarTerceroWSResponse")
    public RespuestaDTO modificarTerceroWS(
        @WebParam(name = "terceroId", targetNamespace = "")
        long terceroId,
        @WebParam(name = "tipoIdentificacionId", targetNamespace = "")
        Tipoidentificacion tipoIdentificacionId,
        @WebParam(name = "identificacionTercero", targetNamespace = "")
        String identificacionTercero,
        @WebParam(name = "nombre", targetNamespace = "")
        String nombre,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "telefonoLocal", targetNamespace = "")
        String telefonoLocal);

    /**
     * 
     * @param terceroId
     * @return
     *     returns com.cbp3.ws.cbp.service.Tercero
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTerceroPorTerceroIdWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaTerceroPorTerceroIdWS")
    @ResponseWrapper(localName = "consultaTerceroPorTerceroIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ConsultaTerceroPorTerceroIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaTerceroPorTerceroIdWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/consultaTerceroPorTerceroIdWSResponse")
    public Tercero consultaTerceroPorTerceroIdWS(
        @WebParam(name = "terceroId", targetNamespace = "")
        long terceroId);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp3.ws.cbp.service.TipoMovimiento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTipoMovimientoWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListTipoMovimientoWS")
    @ResponseWrapper(localName = "listTipoMovimientoWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.ListTipoMovimientoWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listTipoMovimientoWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/listTipoMovimientoWSResponse")
    public List<TipoMovimiento> listTipoMovimientoWS();

    /**
     * 
     * @param descripcionDetalle
     * @param zonaActualId
     * @param terceroId
     * @param fechaMovimiento
     * @param idProductDetalle
     * @param zona
     * @param idOrder
     * @param encargadoMovimiento
     * @param cantidadDetalle
     * @param zonaDestinoId
     * @param idWarehouse
     * @param tipoMovimientoId
     * @param comentarios
     * @param comercioDespachar
     * @return
     *     returns com.cbp3.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generarMovimientoWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.GenerarMovimientoWS")
    @ResponseWrapper(localName = "generarMovimientoWSResponse", targetNamespace = "http://service.cbp.ws.cbp3.com/", className = "com.cbp3.ws.cbp.service.GenerarMovimientoWSResponse")
    @Action(input = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/generarMovimientoWSRequest", output = "http://service.cbp.ws.cbp3.com/InventarioServiceWS/generarMovimientoWSResponse")
    public RespuestaDTO generarMovimientoWS(
        @WebParam(name = "fechaMovimiento", targetNamespace = "")
        XMLGregorianCalendar fechaMovimiento,
        @WebParam(name = "encargadoMovimiento", targetNamespace = "")
        long encargadoMovimiento,
        @WebParam(name = "idWarehouse", targetNamespace = "")
        long idWarehouse,
        @WebParam(name = "tipoMovimientoId", targetNamespace = "")
        TipoMovimiento tipoMovimientoId,
        @WebParam(name = "comentarios", targetNamespace = "")
        String comentarios,
        @WebParam(name = "idOrder", targetNamespace = "")
        long idOrder,
        @WebParam(name = "zona", targetNamespace = "")
        long zona,
        @WebParam(name = "zonaActualId", targetNamespace = "")
        long zonaActualId,
        @WebParam(name = "zonaDestinoId", targetNamespace = "")
        long zonaDestinoId,
        @WebParam(name = "comercioDespachar", targetNamespace = "")
        String comercioDespachar,
        @WebParam(name = "terceroId", targetNamespace = "")
        long terceroId,
        @WebParam(name = "cantidadDetalle", targetNamespace = "")
        long cantidadDetalle,
        @WebParam(name = "descripcionDetalle", targetNamespace = "")
        String descripcionDetalle,
        @WebParam(name = "idProductDetalle", targetNamespace = "")
        long idProductDetalle);

}
