
package com.cbp3.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UbicacionGeograficaWS", targetNamespace = "http://service.cbp.ws.cbp3.com/", wsdlLocation = "http://18.222.73.208:8080/CBP-3/UbicacionGeograficaWS?WSDL")
public class UbicacionGeograficaWS_Service
    extends Service
{

    private final static URL UBICACIONGEOGRAFICAWS_WSDL_LOCATION;
    private final static WebServiceException UBICACIONGEOGRAFICAWS_EXCEPTION;
    private final static QName UBICACIONGEOGRAFICAWS_QNAME = new QName("http://service.cbp.ws.cbp3.com/", "UbicacionGeograficaWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.222.73.208:8080/CBP-3/UbicacionGeograficaWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UBICACIONGEOGRAFICAWS_WSDL_LOCATION = url;
        UBICACIONGEOGRAFICAWS_EXCEPTION = e;
    }

    public UbicacionGeograficaWS_Service() {
        super(__getWsdlLocation(), UBICACIONGEOGRAFICAWS_QNAME);
    }

    public UbicacionGeograficaWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), UBICACIONGEOGRAFICAWS_QNAME, features);
    }

    public UbicacionGeograficaWS_Service(URL wsdlLocation) {
        super(wsdlLocation, UBICACIONGEOGRAFICAWS_QNAME);
    }

    public UbicacionGeograficaWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UBICACIONGEOGRAFICAWS_QNAME, features);
    }

    public UbicacionGeograficaWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UbicacionGeograficaWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UbicacionGeograficaWS
     */
    @WebEndpoint(name = "UbicacionGeograficaWSPort")
    public UbicacionGeograficaWS getUbicacionGeograficaWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "UbicacionGeograficaWSPort"), UbicacionGeograficaWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UbicacionGeograficaWS
     */
    @WebEndpoint(name = "UbicacionGeograficaWSPort")
    public UbicacionGeograficaWS getUbicacionGeograficaWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp3.com/", "UbicacionGeograficaWSPort"), UbicacionGeograficaWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UBICACIONGEOGRAFICAWS_EXCEPTION!= null) {
            throw UBICACIONGEOGRAFICAWS_EXCEPTION;
        }
        return UBICACIONGEOGRAFICAWS_WSDL_LOCATION;
    }

}
