
package com.cbp1.ws.cbp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AccountWS", targetNamespace = "http://service.cbp.ws.cbp1.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountWS {


    /**
     * 
     * @param clientDocumentId
     * @param accountType
     * @param officeCode
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccountWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateAccountWS")
    @ResponseWrapper(localName = "createAccountWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateAccountWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/AccountWS/createAccountWSRequest", output = "http://service.cbp.ws.cbp1.com/AccountWS/createAccountWSResponse")
    public RespuestaDTO createAccountWS(
        @WebParam(name = "officeCode", targetNamespace = "")
        String officeCode,
        @WebParam(name = "accountType", targetNamespace = "")
        String accountType,
        @WebParam(name = "clientDocumentId", targetNamespace = "")
        String clientDocumentId);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cbp1.ws.cbp.service.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultAcoountByClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultAcoountByClientWS")
    @ResponseWrapper(localName = "consultAcoountByClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultAcoountByClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/AccountWS/consultAcoountByClientWSRequest", output = "http://service.cbp.ws.cbp1.com/AccountWS/consultAcoountByClientWSResponse")
    public Account consultAcoountByClientWS(
        @WebParam(name = "clientId", targetNamespace = "")
        String clientId);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.ClientDTO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllAccountAndClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.FindAllAccountAndClientWS")
    @ResponseWrapper(localName = "findAllAccountAndClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.FindAllAccountAndClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/AccountWS/findAllAccountAndClientWSRequest", output = "http://service.cbp.ws.cbp1.com/AccountWS/findAllAccountAndClientWSResponse")
    public List<ClientDTO> findAllAccountAndClientWS();

    /**
     * 
     * @param documentClientId
     * @param commentsStatus
     * @param statusAccount
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStatusAccountWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateStatusAccountWS")
    @ResponseWrapper(localName = "updateStatusAccountWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateStatusAccountWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/AccountWS/updateStatusAccountWSRequest", output = "http://service.cbp.ws.cbp1.com/AccountWS/updateStatusAccountWSResponse")
    public RespuestaDTO updateStatusAccountWS(
        @WebParam(name = "documentClientId", targetNamespace = "")
        String documentClientId,
        @WebParam(name = "statusAccount", targetNamespace = "")
        String statusAccount,
        @WebParam(name = "commentsStatus", targetNamespace = "")
        String commentsStatus);

}
