
package com.cbp1.ws.cbp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CardWS", targetNamespace = "http://service.cbp.ws.cbp1.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CardWS {


    /**
     * 
     * @param plastic
     * @param fechaCorte
     * @param fechaAsignacion
     * @param client
     * @param canal
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "assignCardToClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.AssignCardToClientWS")
    @ResponseWrapper(localName = "assignCardToClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.AssignCardToClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/CardWS/assignCardToClientWSRequest", output = "http://service.cbp.ws.cbp1.com/CardWS/assignCardToClientWSResponse")
    public RespuestaDTO assignCardToClientWS(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "plastic", targetNamespace = "")
        Plastic plastic,
        @WebParam(name = "fechaCorte", targetNamespace = "")
        String fechaCorte,
        @WebParam(name = "fechaAsignacion", targetNamespace = "")
        String fechaAsignacion,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

    /**
     * 
     * @param client
     * @param canal
     * @param status
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelCardWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CancelCardWS")
    @ResponseWrapper(localName = "cancelCardWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CancelCardWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/CardWS/cancelCardWSRequest", output = "http://service.cbp.ws.cbp1.com/CardWS/cancelCardWSResponse")
    public RespuestaDTO cancelCardWS(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

    /**
     * 
     * @param plasticNumber
     * @return
     *     returns com.cbp1.ws.cbp.service.Plastic
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultPlasticByNumberWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultPlasticByNumberWS")
    @ResponseWrapper(localName = "consultPlasticByNumberWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultPlasticByNumberWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/CardWS/consultPlasticByNumberWSRequest", output = "http://service.cbp.ws.cbp1.com/CardWS/consultPlasticByNumberWSResponse")
    public Plastic consultPlasticByNumberWS(
        @WebParam(name = "plasticNumber", targetNamespace = "")
        String plasticNumber);

}
