
package com.cbp1.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CardWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", wsdlLocation = "http://18.223.203.6:8080/CBP-1/CardWS?wsdl")
public class CardWS_Service
    extends Service
{

    private final static URL CARDWS_WSDL_LOCATION;
    private final static WebServiceException CARDWS_EXCEPTION;
    private final static QName CARDWS_QNAME = new QName("http://service.cbp.ws.cbp1.com/", "CardWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.223.203.6:8080/CBP-1/CardWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDWS_WSDL_LOCATION = url;
        CARDWS_EXCEPTION = e;
    }

    public CardWS_Service() {
        super(__getWsdlLocation(), CARDWS_QNAME);
    }

    public CardWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDWS_QNAME, features);
    }

    public CardWS_Service(URL wsdlLocation) {
        super(wsdlLocation, CARDWS_QNAME);
    }

    public CardWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDWS_QNAME, features);
    }

    public CardWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CardWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CardWS
     */
    @WebEndpoint(name = "CardWSPort")
    public CardWS getCardWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "CardWSPort"), CardWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CardWS
     */
    @WebEndpoint(name = "CardWSPort")
    public CardWS getCardWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "CardWSPort"), CardWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDWS_EXCEPTION!= null) {
            throw CARDWS_EXCEPTION;
        }
        return CARDWS_WSDL_LOCATION;
    }

}
