
package com.cbp1.ws.cbp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientWS {


    /**
     * 
     * @param idClient
     * @return
     *     returns com.cbp1.ws.cbp.service.InformacionAdicionalClienteDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultAllClientByIdClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultAllClientByIdClientWS")
    @ResponseWrapper(localName = "consultAllClientByIdClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultAllClientByIdClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/consultAllClientByIdClientWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/consultAllClientByIdClientWSResponse")
    public InformacionAdicionalClienteDTO consultAllClientByIdClientWS(
        @WebParam(name = "idClient", targetNamespace = "")
        long idClient);

    /**
     * 
     * @param dto
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "actualizaClienteConInformacionAdicionalWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ActualizaClienteConInformacionAdicionalWS")
    @ResponseWrapper(localName = "actualizaClienteConInformacionAdicionalWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ActualizaClienteConInformacionAdicionalWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/actualizaClienteConInformacionAdicionalWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/actualizaClienteConInformacionAdicionalWSResponse")
    public RespuestaDTO actualizaClienteConInformacionAdicionalWS(
        @WebParam(name = "dto", targetNamespace = "")
        InformacionAdicionalClienteDTO dto);

    /**
     * 
     * @param distrito
     * @return
     *     returns com.cbp1.ws.cbp.service.CodigoPostal
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "codigoPostalWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CodigoPostalWS")
    @ResponseWrapper(localName = "codigoPostalWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CodigoPostalWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/codigoPostalWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/codigoPostalWSResponse")
    public CodigoPostal codigoPostalWS(
        @WebParam(name = "distrito", targetNamespace = "")
        Distrito distrito);

    /**
     * 
     * @param idClient
     * @param dto
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveAditionaInformationClient", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.SaveAditionaInformationClient")
    @ResponseWrapper(localName = "saveAditionaInformationClientResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.SaveAditionaInformationClientResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/saveAditionaInformationClientRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/saveAditionaInformationClientResponse")
    public RespuestaDTO saveAditionaInformationClient(
        @WebParam(name = "dto", targetNamespace = "")
        InformacionAdicionalClienteDTO dto,
        @WebParam(name = "idClient", targetNamespace = "")
        long idClient);

    /**
     * 
     * @param nombreUsuario
     * @return
     *     returns com.cbp1.ws.cbp.service.ValidaClientDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultClientByUsersFpWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultClientByUsersFpWS")
    @ResponseWrapper(localName = "consultClientByUsersFpWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultClientByUsersFpWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/consultClientByUsersFpWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/consultClientByUsersFpWSResponse")
    public ValidaClientDTO consultClientByUsersFpWS(
        @WebParam(name = "nombreUsuario", targetNamespace = "")
        String nombreUsuario);

    /**
     * 
     * @param idCanal
     * @param nombreCanal
     * @param clientDTO
     * @param nombreUsuario
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createClientsWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateClientsWS")
    @ResponseWrapper(localName = "createClientsWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateClientsWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/createClientsWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/createClientsWSResponse")
    public RespuestaDTO createClientsWS(
        @WebParam(name = "clientDTO", targetNamespace = "")
        NewClientDTO clientDTO,
        @WebParam(name = "nombreUsuario", targetNamespace = "")
        String nombreUsuario,
        @WebParam(name = "idCanal", targetNamespace = "")
        String idCanal,
        @WebParam(name = "nombreCanal", targetNamespace = "")
        String nombreCanal);

    /**
     * 
     * @param clientId
     * @return
     *     returns com.cbp1.ws.cbp.service.Documents
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultClientWS")
    @ResponseWrapper(localName = "consultClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/consultClientWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/consultClientWSResponse")
    public Documents consultClientWS(
        @WebParam(name = "clientId", targetNamespace = "")
        String clientId);

    /**
     * 
     * @param clientDTO
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateClientWS")
    @ResponseWrapper(localName = "updateClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/updateClientWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/updateClientWSResponse")
    public RespuestaDTO updateClientWS(
        @WebParam(name = "clientDTO", targetNamespace = "")
        NewClientDTO clientDTO);

    /**
     * 
     * @param idCanal
     * @param cargaArchivosDTO
     * @param nombreCanal
     * @param clientDocumentId
     * @return
     *     returns com.cbp1.ws.cbp.service.CargaArchivosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "procesarArchivosClienteWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ProcesarArchivosClienteWS")
    @ResponseWrapper(localName = "procesarArchivosClienteWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ProcesarArchivosClienteWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/procesarArchivosClienteWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/procesarArchivosClienteWSResponse")
    public CargaArchivosDTO procesarArchivosClienteWS(
        @WebParam(name = "cargaArchivosDTO", targetNamespace = "")
        CargaArchivosDTO cargaArchivosDTO,
        @WebParam(name = "clientDocumentId", targetNamespace = "")
        String clientDocumentId,
        @WebParam(name = "idCanal", targetNamespace = "")
        String idCanal,
        @WebParam(name = "nombreCanal", targetNamespace = "")
        String nombreCanal);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.Client>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listClientsWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListClientsWS")
    @ResponseWrapper(localName = "listClientsWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListClientsWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listClientsWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listClientsWSResponse")
    public List<Client> listClientsWS();

    /**
     * 
     * @param idCanal
     * @param cargaArchivosDTO
     * @param nombreCanal
     * @param clientDocumentId
     * @return
     *     returns com.cbp1.ws.cbp.service.CargaArchivosDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateDocumentsClientWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateDocumentsClientWS")
    @ResponseWrapper(localName = "updateDocumentsClientWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.UpdateDocumentsClientWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/updateDocumentsClientWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/updateDocumentsClientWSResponse")
    public CargaArchivosDTO updateDocumentsClientWS(
        @WebParam(name = "cargaArchivosDTO", targetNamespace = "")
        CargaArchivosDTO cargaArchivosDTO,
        @WebParam(name = "clientDocumentId", targetNamespace = "")
        String clientDocumentId,
        @WebParam(name = "idCanal", targetNamespace = "")
        String idCanal,
        @WebParam(name = "nombreCanal", targetNamespace = "")
        String nombreCanal);

    /**
     * 
     * @param idDocumentClient
     * @return
     *     returns com.cbp1.ws.cbp.service.ValidaClientDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validaClientbyDocumentIdWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ValidaClientbyDocumentIdWS")
    @ResponseWrapper(localName = "validaClientbyDocumentIdWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ValidaClientbyDocumentIdWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/validaClientbyDocumentIdWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/validaClientbyDocumentIdWSResponse")
    public ValidaClientDTO validaClientbyDocumentIdWS(
        @WebParam(name = "idDocumentClient", targetNamespace = "")
        String idDocumentClient);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.Pais>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listPaisWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListPaisWS")
    @ResponseWrapper(localName = "listPaisWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListPaisWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listPaisWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listPaisWSResponse")
    public List<Pais> listPaisWS();

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.CategoriaOcupacional>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCatOcupacionalWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListCatOcupacionalWS")
    @ResponseWrapper(localName = "listCatOcupacionalWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListCatOcupacionalWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listCatOcupacionalWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listCatOcupacionalWSResponse")
    public List<CategoriaOcupacional> listCatOcupacionalWS();

    /**
     * 
     * @param pais
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.Provincia>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listProvinciasWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListProvinciasWS")
    @ResponseWrapper(localName = "listProvinciasWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListProvinciasWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listProvinciasWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listProvinciasWSResponse")
    public List<Provincia> listProvinciasWS(
        @WebParam(name = "pais", targetNamespace = "")
        Pais pais);

    /**
     * 
     * @param provincia
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.Canton>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCantonWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListCantonWS")
    @ResponseWrapper(localName = "listCantonWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListCantonWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listCantonWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listCantonWSResponse")
    public List<Canton> listCantonWS(
        @WebParam(name = "provincia", targetNamespace = "")
        Provincia provincia);

    /**
     * 
     * @param canton
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.Distrito>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listDistritoWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListDistritoWS")
    @ResponseWrapper(localName = "listDistritoWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListDistritoWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listDistritoWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listDistritoWSResponse")
    public List<Distrito> listDistritoWS(
        @WebParam(name = "canton", targetNamespace = "")
        Canton canton);

    /**
     * 
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.EntityBank>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listBanksWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListBanksWS")
    @ResponseWrapper(localName = "listBanksWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListBanksWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/ClientWS/listBanksWSRequest", output = "http://service.cbp.ws.cbp1.com/ClientWS/listBanksWSResponse")
    public List<EntityBank> listBanksWS();

}
