
package com.cbp1.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClientsWs", targetNamespace = "http://service.cbp.ws.cbp1.com/", wsdlLocation = "http://18.223.203.6:8080/CBP-1/ClientsWs?WSDL")
public class ClientsWs
    extends Service
{

    private final static URL CLIENTSWS_WSDL_LOCATION;
    private final static WebServiceException CLIENTSWS_EXCEPTION;
    private final static QName CLIENTSWS_QNAME = new QName("http://service.cbp.ws.cbp1.com/", "ClientsWs");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.223.203.6:8080/CBP-1/ClientsWs?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTSWS_WSDL_LOCATION = url;
        CLIENTSWS_EXCEPTION = e;
    }

    public ClientsWs() {
        super(__getWsdlLocation(), CLIENTSWS_QNAME);
    }

    public ClientsWs(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTSWS_QNAME, features);
    }

    public ClientsWs(URL wsdlLocation) {
        super(wsdlLocation, CLIENTSWS_QNAME);
    }

    public ClientsWs(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTSWS_QNAME, features);
    }

    public ClientsWs(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientsWs(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public ClientWS getClientWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "ClientWSPort"), ClientWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientWS
     */
    @WebEndpoint(name = "ClientWSPort")
    public ClientWS getClientWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "ClientWSPort"), ClientWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTSWS_EXCEPTION!= null) {
            throw CLIENTSWS_EXCEPTION;
        }
        return CLIENTSWS_WSDL_LOCATION;
    }

}
