
package com.cbp1.ws.cbp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TdcRequestWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", wsdlLocation = "http://18.222.73.208:8080/CBP-1/TdcRequestWS?wsdl")
public class TdcRequestWS_Service
    extends Service
{

    private final static URL TDCREQUESTWS_WSDL_LOCATION;
    private final static WebServiceException TDCREQUESTWS_EXCEPTION;
    private final static QName TDCREQUESTWS_QNAME = new QName("http://service.cbp.ws.cbp1.com/", "TdcRequestWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://18.222.73.208:8080/CBP-1/TdcRequestWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TDCREQUESTWS_WSDL_LOCATION = url;
        TDCREQUESTWS_EXCEPTION = e;
    }

    public TdcRequestWS_Service() {
        super(__getWsdlLocation(), TDCREQUESTWS_QNAME);
    }

    public TdcRequestWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TDCREQUESTWS_QNAME, features);
    }

    public TdcRequestWS_Service(URL wsdlLocation) {
        super(wsdlLocation, TDCREQUESTWS_QNAME);
    }

    public TdcRequestWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TDCREQUESTWS_QNAME, features);
    }

    public TdcRequestWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TdcRequestWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TdcRequestWS
     */
    @WebEndpoint(name = "TdcRequestWSPort")
    public TdcRequestWS getTdcRequestWSPort() {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "TdcRequestWSPort"), TdcRequestWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TdcRequestWS
     */
    @WebEndpoint(name = "TdcRequestWSPort")
    public TdcRequestWS getTdcRequestWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.cbp.ws.cbp1.com/", "TdcRequestWSPort"), TdcRequestWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TDCREQUESTWS_EXCEPTION!= null) {
            throw TDCREQUESTWS_EXCEPTION;
        }
        return TDCREQUESTWS_WSDL_LOCATION;
    }

}
