
package com.cbp1.ws.cbp.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TdcRequestWS", targetNamespace = "http://service.cbp.ws.cbp1.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TdcRequestWS {


    /**
     * 
     * @param tdcRequest
     * @param statusTdcRequest
     * @param canal
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "denyTdcRequestWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.DenyTdcRequestWS")
    @ResponseWrapper(localName = "denyTdcRequestWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.DenyTdcRequestWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/TdcRequestWS/denyTdcRequestWSRequest", output = "http://service.cbp.ws.cbp1.com/TdcRequestWS/denyTdcRequestWSResponse")
    public RespuestaDTO denyTdcRequestWS(
        @WebParam(name = "tdcRequest", targetNamespace = "")
        TdcRequest tdcRequest,
        @WebParam(name = "statusTdcRequest", targetNamespace = "")
        String statusTdcRequest,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

    /**
     * 
     * @param client
     * @param canal
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTdcRequestWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateTdcRequestWS")
    @ResponseWrapper(localName = "createTdcRequestWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.CreateTdcRequestWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/TdcRequestWS/createTdcRequestWSRequest", output = "http://service.cbp.ws.cbp1.com/TdcRequestWS/createTdcRequestWSResponse")
    public RespuestaDTO createTdcRequestWS(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

    /**
     * 
     * @param nombreCanal
     * @param statusTdcRequest
     * @return
     *     returns java.util.List<com.cbp1.ws.cbp.service.TdcRequest>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listTdcRequestByStatusWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListTdcRequestByStatusWS")
    @ResponseWrapper(localName = "listTdcRequestByStatusWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ListTdcRequestByStatusWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/TdcRequestWS/listTdcRequestByStatusWSRequest", output = "http://service.cbp.ws.cbp1.com/TdcRequestWS/listTdcRequestByStatusWSResponse")
    public List<TdcRequest> listTdcRequestByStatusWS(
        @WebParam(name = "statusTdcRequest", targetNamespace = "")
        String statusTdcRequest,
        @WebParam(name = "nombreCanal", targetNamespace = "")
        String nombreCanal);

    /**
     * 
     * @param tdcRequest
     * @param statusTdcRequest
     * @param canal
     * @return
     *     returns com.cbp1.ws.cbp.service.RespuestaDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "approveTdcRequestWS", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ApproveTdcRequestWS")
    @ResponseWrapper(localName = "approveTdcRequestWSResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ApproveTdcRequestWSResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/TdcRequestWS/approveTdcRequestWSRequest", output = "http://service.cbp.ws.cbp1.com/TdcRequestWS/approveTdcRequestWSResponse")
    public RespuestaDTO approveTdcRequestWS(
        @WebParam(name = "tdcRequest", targetNamespace = "")
        TdcRequest tdcRequest,
        @WebParam(name = "statusTdcRequest", targetNamespace = "")
        String statusTdcRequest,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

    /**
     * 
     * @param statusTdcRequest
     * @param client
     * @param canal
     * @return
     *     returns com.cbp1.ws.cbp.service.TdcRequest
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultTdcRequest", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultTdcRequest")
    @ResponseWrapper(localName = "consultTdcRequestResponse", targetNamespace = "http://service.cbp.ws.cbp1.com/", className = "com.cbp1.ws.cbp.service.ConsultTdcRequestResponse")
    @Action(input = "http://service.cbp.ws.cbp1.com/TdcRequestWS/consultTdcRequestRequest", output = "http://service.cbp.ws.cbp1.com/TdcRequestWS/consultTdcRequestResponse")
    public TdcRequest consultTdcRequest(
        @WebParam(name = "client", targetNamespace = "")
        Client client,
        @WebParam(name = "statusTdcRequest", targetNamespace = "")
        String statusTdcRequest,
        @WebParam(name = "canal", targetNamespace = "")
        String canal);

}
